# xkbwatch
# Autogenerated from man page /usr/share/man/man1/xkbwatch.1
complete -c xkbwatch -o version --description 'This option indicates that the program version should be printed, after which…'

